import type { Env as GoodvoiceEnv } from "./env";

// Wrangler and the Vitest pool both type bindings through `Cloudflare.Env`.
// Merging our hand-written `Env` into it keeps one source of truth instead of a
// generated `worker-configuration.d.ts` that would have to be regenerated by
// hand every time a binding changes.
declare global {
  namespace Cloudflare {
    interface Env extends GoodvoiceEnv {}
  }
}

export {};
